"""
split_day01_assets.py
======================
Splits the combined Day 1 JSON assets into per-sub-topic files.

Creates in generated_content/day_01/splits/:
  Lab Manuals (one per sub-topic):
    lab_d01_01_jvm_platform.json
    lab_d01_02_primitives.json
    lab_d01_03_operators.json
    lab_d01_04_flow_control.json
    lab_d01_05_arrays.json
    lab_d01_06_capstone.json

  Flashcard Sets (one per sub-topic):
    fc_d01_01_jvm_platform.json
    fc_d01_02_primitives.json
    fc_d01_03_operators.json
    fc_d01_04_flow_control.json
    fc_d01_05_arrays.json
    fc_d01_06_best_practices.json

  Notes: Already split per section in notes_day_01.json;
         HTML files generated by generate_session_html.py
"""

import json
from pathlib import Path

BASE = Path(__file__).parent / "generated_content" / "day_01"
OUT  = BASE / "splits"
OUT.mkdir(parents=True, exist_ok=True)

# ─── Load source files ────────────────────────────────────────────────────────

with open(BASE / "lab_day_01.json", encoding="utf-8") as f:
    lab_src = json.load(f)

with open(BASE / "fc_concept_beginner_01.json", encoding="utf-8") as f:
    fc_src = json.load(f)

# ─── Lab Manual splits ────────────────────────────────────────────────────────

LAB_TOPICS = [
    ("01", "jvm_platform",  "JVM, JDK & JRE — Java Platform Architecture",  "LAB_01", 20),
    ("02", "primitives",    "Primitive Data Types & Ranges",                  "LAB_02", 25),
    ("03", "operators",     "Operators & EMI Calculator",                     "LAB_03", 30),
    ("04", "flow_control",  "Flow Control — ATM Simulator",                   "LAB_04", 35),
    ("05", "arrays",        "Arrays & Arrays Utility Class",                  "LAB_05", 35),
    ("06", "capstone",      "Capstone Lab — Mini Bank Statement Generator",   "LAB_06", 35),
]

exercises_by_id = {ex["exercise_id"]: ex for ex in lab_src["exercises"]}

print("=" * 60)
print("LAB MANUALS — per sub-topic")
print("=" * 60)

for num, slug, topic, exercise_id, duration in LAB_TOPICS:
    exercise = exercises_by_id.get(exercise_id)
    if not exercise:
        print(f"  WARNING: Exercise {exercise_id} not found in source!")
        continue

    doc = {
        "meta": {
            "asset_type": "lab_manual",
            "session_day": 1,
            "topic": topic,
            "sub_topic_num": int(num),
            "session_title": lab_src["meta"]["session_title"],
            "date": lab_src["meta"]["date"],
            "duration_minutes": duration,
            "total_exercises": 1,
            "generated_by": lab_src["meta"]["generated_by"],
            "pedagogy": lab_src["meta"]["pedagogy"],
        },
        "overview": {
            "objectives": [exercise.get("objective", topic)],
            "prerequisites": lab_src["overview"]["prerequisites"],
            "tools": lab_src["overview"]["tools"],
        },
        "exercises": [exercise],
    }

    out_file = OUT / f"lab_d01_{num}_{slug}.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
    size = out_file.stat().st_size / 1024
    print(f"  OK  {out_file.name}  ({size:.1f} KB)")

# ─── Flashcard Set splits ────────────────────────────────────────────────────

FC_GROUPS = [
    ("01", "jvm_platform",    "JVM, JDK & JRE — Platform Architecture",
     ["FC_001", "FC_019"]),
    ("02", "primitives",      "Primitive Data Types & Type Conversion",
     ["FC_003", "FC_004", "FC_013"]),
    ("03", "operators",       "Operators, Short-Circuit & Precision",
     ["FC_002", "FC_005", "FC_006", "FC_007", "FC_012", "FC_014"]),
    ("04", "flow_control",    "Flow Control — Loops, Switch & Break/Continue",
     ["FC_008", "FC_009", "FC_010"]),
    ("05", "arrays",          "Arrays, Varargs & java.util.Arrays",
     ["FC_011", "FC_015", "FC_016", "FC_020"]),
    ("06", "best_practices",  "Best Practices, Naming Conventions & NullPointerException",
     ["FC_017", "FC_018"]),
]

cards_by_id = {c["card_id"]: c for c in fc_src["cards"]}

print()
print("=" * 60)
print("FLASHCARD SETS — per sub-topic")
print("=" * 60)

for num, slug, topic, card_ids in FC_GROUPS:
    cards = []
    for i, cid in enumerate(card_ids, start=1):
        if cid not in cards_by_id:
            print(f"  WARNING: Card {cid} not found!")
            continue
        card = dict(cards_by_id[cid])  # shallow copy
        card["order"] = i
        cards.append(card)

    doc = {
        "meta": {
            "asset_type": "flashcard",
            "session_day": 1,
            "topic": topic,
            "sub_topic_num": int(num),
            "session_title": fc_src["meta"]["session_title"],
            "total_cards": len(cards),
            "generated_by": fc_src["meta"]["generated_by"],
            "pedagogy": fc_src["meta"]["pedagogy"],
        },
        "cards": cards,
    }

    out_file = OUT / f"fc_d01_{num}_{slug}.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
    size = out_file.stat().st_size / 1024
    print(f"  OK  {out_file.name}  ({size:.1f} KB)  [{len(cards)} cards]")

# ─── Summary ─────────────────────────────────────────────────────────────────

splits = sorted(OUT.glob("*.json"))
print(f"\nDone — {len(splits)} split files created in:\n  {OUT}")
print()
for f in splits:
    print(f"  {f.name}")
